server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
      force-request: true
      force-response: true

spring:
  application:
    name: phoenix-dfs

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


phoenix-dfs:
  path: ${user.home}/phoenix-dfs
  backup-url: http://localhost:8081/upload