server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
      force-request: true
      force-response: true

spring:
  application:
    name: phoenix-dfs

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


rocketmq:
  name-server: 192.168.200.39:9876
  producer:
    group: phoenix-dfs-producer


phoenix-dfs:
  sync-backup: false
  auto-md5: true
  group: C8080
  upload-path: ${user.home}/phoenix-dfs
  backup-url: http://localhost:8081/upload
  download-url: http://localhost:8080/download
